#!/bin/sh

# Read all about UCI defaults at
# https://openwrt.org/docs/guide-developer/uci-defaults

# Note that scripts in /etc/uci-defaults will get executed at *every* first
# boot (i.e. after both factory install as well as upgrades),
# possibly overwriting already existing values!
# scripts in this dir should *not* be executable

# Below we will set the ip address to seomthing that isn't normally 
# what other routers set as their default ip address
# however, this isn't bullet-proof. 
# You can't have 2 router doing dhcp, so we need to
# setup a lan ip, which isn't your typical ip.
# TODO: this is something we need to look into nomre
# uci set network.lan.ipaddr='192.168.1.10'
# uci set network.lan.netmask='255.255.255.0'
# uci commit network

# not every wifi will be in mexico
# TODO: figure out how to get country code
# or make that part of the on-boarding setup
#uci set wireless.radio0.country='MX'
#uci set wireless.radio0.disabled='0'
#uci commit wireless

# /etc/init.d/network restart

# uci -q batch << EOI
# set network.lan.ipaddr='192.168.178.1'
# set wireless.@wifi-device[0].disabled='0'
# set wireless.@wifi-iface[0].ssid='OpenWrt0815'
# add dhcp host
# set dhcp.@host[-1].name='bellerophon'
# set dhcp.@host[-1].ip='192.168.2.100'
# set dhcp.@host[-1].mac='a1:b2:c3:d4:e5:f6'
# rename firewall.@zone[0]='lan'
# rename firewall.@zone[1]='wan'
# rename firewall.@forwarding[0]='lan_wan'
# EOI

uci -q batch << EOI
set wireless.@wifi-device[0].disabled='0'
set wireless.@wifi-iface[0].ssid='OpenWrt0815'
EOI
exit 0
