#!/bin/sh

# Read all about UCI defaults at
# https://openwrt.org/docs/guide-developer/uci-defaults

# Note that scripts in /etc/uci-defaults will get executed at *every* first
# boot (i.e. after both factory install as well as upgrades),
# possibly overwriting already existing values!
# scripts in this dir should *not* be executable

# Below we will set the ip address to seomthing that isn't normally 
# what other routers set as their default ip address
# however, this isn't bullet-proof. 
# You can't have 2 router doing dhcp, so we need to
# setup a lan ip, which isn't your typical ip.
# TODO: this is something we need to look into nomre
# uci set network.lan.ipaddr='192.168.1.10'
# uci set network.lan.netmask='255.255.255.0'
# uci commit network

# not every wifi will be in mexico
# TODO: figure out how to get country code
# or make that part of the on-boarding setup
uci set wireless.radio0.country='MX'
uci set wireless.radio0.disabled='0'
uci commit wireless

# /etc/init.d/network restart

exit 0
